[project]
name = "hubspot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.10",
    "psycopg2-binary>=2.9.9",
    "python-dotenv>=1.0.0",
    "hubspot-api-client>=9.0.0",
    "requests>=2.31.0",
]
